apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cid
  labels:
    app: cid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cid
  template:
    metadata:
      labels:
        app: cid
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: cid
        image: bmsdave/piterjs-cid:v0.0.1
        env:
          - name: ACCESSKEY
            value: "***"
          - name: SECRETKEY
            value: "***"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cid
  labels:
    app: cid
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: cid
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cid
  labels:
    app: cid
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - cid.piterjs.org
      secretName: cid-k8-piterjs-tls
  rules:
    - host: cid.piterjs.org
      http:
        paths:
         - path: /
           backend:
             serviceName: cid
             servicePort: 80
